import type { Metadata } from "next";
import "./globals.css";
import Header from "./header";
import { Poppins } from "next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "600", "700"], // choose weights you want
  variable: "--font-poppins",
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`h-dvh w-dvw flex flex-col antialiased overflow-x-hidden ${poppins.variable}`}
      >
        <Header />
        <main className="flex-1 w-full">{children}</main>
      </body>
    </html>
  );
}
